language: csharp
solution: DDDPizza.sln
install:
  - nuget restore DDDPizzaInc.sln
 script:
  - xbuild /p:Configuration=Release DDDPizzaInc.sln
  - mono ./packages/NUnit.Runners.2.6.4/tools/nunit-console.exe ./DDDPizzaInc.UnitTests/bin/Release/DDDPizzaInc.UnitTests.dll
